package.json, scripts/npm-pack-testing.sh, src/server/event-stream-manager.ts
fix: https://github.com/juzibot/donut-tester/issues/9
=> Fix multi listener bug

package.json, src/client/puppet-hostie.ts
Related issue: https://github.com/wechaty/wechaty-puppet-hostie/issues/36
=> Friendship payload

package.json, src/server/puppet-implementation.ts
Related issue: https://github.com/wechaty/wechaty-puppet-hostie/issues/36
=> Set contactId for friendshipPayload in puppet-implementation

package.json, src/client/puppet-hostie.ts, src/config.ts, src/server/puppet-server.ts
Related issue: https://github.com/wechaty/wechaty-puppet-hostie/issues/41
=> Add GPRC send or received message length limitation.

package.json, src/client/puppet-hostie.ts
Related issue: https://github.com/wechaty/wechaty-puppet-hostie/issues/48
=> Remove logout event in logout()

package.json, src/server/puppet-implementation.ts
=> fix ready event before login event issue

package.json, src/client/puppet-hostie.ts
Refer to issue: https://github.com/wechaty/wechaty-puppet-hostie/issues/70
=> fix client reconnection error

package.json, src/stream/file-box-helper.spec.ts, src/stream/file-box-helper.ts, src/stream/message-send-file-stream-request.spec.ts, src/stream/message-send-file-stream-request.ts
=> Import file box from wechaty puppet

package.json, src/client/puppet-hostie.ts, src/server/puppet-implementation.ts, src/server/serialize-file-box.ts
Related to https://github.com/wechaty/wechaty-puppet-hostie/issues/90
=> Fix serialize file box bug

package.json, src/client/puppet-hostie.ts
Related to https://github.com/wechaty/wechaty-puppet-hostie/discussions/115
To save some bandwidth and network traffic by using non stream method to send url filebox.
=> Non stream send url filebox

.github/workflows/npm.yml, README.md, package.json, src/client/puppet-hostie.spec.ts, src/client/puppet-hostie.ts, src/config.ts, tests/fixtures/smoke-testing.ts, tests/integration.spec.ts, tests/performance.spec.ts
=> Rename from puppet-hostie -> puppet-service (#118)

examples/ding-dong-bot.ts, package.json, src/client/puppet-service.ts, src/config.ts, src/server/event-stream-manager.ts, src/server/grpc-error.ts, src/server/puppet-implementation.ts, src/server/puppet-server.ts, src/typings.d.ts
=> Use Pure JS gRPC

package.json, src/server/puppet-implementation.ts
Related issue: https://github.com/wechaty/wechaty-puppet-service/issues/146
=> Set receiver

README.md, package.json, src/client/puppet-service.ts, src/config.spec.ts, src/config.ts
=> Enable gRPC authority discovery resolver for Wechaty

package.json, src/client/puppet-service.ts, src/server/puppet-implementation.ts
Related issue: https://github.com/wechaty/wechaty/issues/2250
=> Location message

package.json, src/client/puppet-service.ts, src/server/puppet-implementation.ts
Related to
- https://github.com/wechaty/grpc/issues/109
=> Deprecate StringValue wrappers

package.json, src/client/puppet-service.ts, src/server/puppet-implementation.ts
Related to 
- https://github.com/wechaty/grpc/issues/109
=> deprecated & compatible with StringValue wrappers

package.json, src/server/event-stream-manager.ts, tests/ready-event.spec.ts
Will add a test when https://github.com/wechaty/puppet/pull/179 gets merged
=> feat: 🎸 emit a ready event when trying to start a ready puppet

package.json, src/client/duck/actions.ts, src/client/duck/epic-recover.spec.ts, src/client/duck/epic-recover.ts, src/client/duck/operations.ts, src/client/duck/reducers.ts, src/client/duck/types.ts, src/client/puppet-service.ts, src/server/puppet-implementation.ts
Related to
- https://github.com/wechaty/puppet/issues/181
=> deprecated `weixin` with `handle

package.json, src/client/duck/epic-recover.spec.ts, src/client/duck/epic-recover.ts, src/client/puppet-service.ts
=> fix: 🐛 room member cache key

package.json, src/server/event-stream-manager.ts, tests/ready-event.spec.ts
=> Feat delay ready

.eslintrc.cjs, src/auth/auth-impl-token.ts, src/auth/ca.spec.ts, src/client/puppet-service.spec.ts, src/server/puppet-server.ts, tests/grpc-stream.spec.ts, tests/integration.spec.ts, tests/performance.spec.ts, tests/ready-event.spec.ts, tests/uuid-file-box.spec.ts, tsconfig.json
https://github.com/wechaty/puppet-service/issues/233
=> fix ci and lint
